### ISSUE TITLE
Mod doesn't disable Swimming or Sprinting [Forge - 1.18.2]

### ISSUE THREAD

**Issue by Shadowdragon019** [iGalaxyYT/take-it-slow#1]
I've tried messing with config options but nothing happens at all

Example vid - https://youtu.be/slLyHwBCA3s

**Comment by wiidotmom** [comment]
Hm, I figured out why I didn't catch this in the first place - doesn't occur in forge:runClient (local testing) for some reason. Will look into this.

**Comment by wiidotmom** [comment]
Found a fix. https://github.com/iGalaxyYT/take-it-slow/commit/5b64eac290d1050967c72304c8a33b3134154342
Will release soon

**Comment by wiidotmom** [comment]
See https://github.com/iGalaxyYT/take-it-slow/releases/tag/v1.0.3
