### ISSUE TITLE
Gamerules?

### ISSUE THREAD

**Issue by TheBiggestHuman** [iGalaxyYT/take-it-slow#3]
Hello,

I am wondering if you could add the ability to allow disabling sprint through gamerules instead of just the config? Maybe the ability to enable gamerule functionality from the config, so you can either enforce disabled sprint or make it optional?

Thank you!

**Comment by wiidotmom** [comment]
This is kinda out-of-scope, the intention is to be a client-only mod. Gamerules are server-side.
